---
ID: "94ead77c-4b5c-4a11-9be5-a107c8c3b95f"
Parent: "d55741f0-482d-4001-9230-f8ffc391f06a"
Template: "d55741f0-482d-4001-9230-f8ffc391f06a"
Path: /sitecore/templates/Project/edgewebsite/Site Config/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {76036F5E-CBCE-46D1-AF0A-4143F9B557AA}
    {A87A00B1-E6DB-45AB-8B54-636FEC3B5523}
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{A5BC37E7-ED96-4C1E-8590-A26E64DB55EA}"
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{14030E9F-CE92-49C6-AD87-7D49B50E42EA}">
        <r
          ds=""
          id="{885B8314-7D8C-4CBB-8000-01421EA8F406}"
          par=""
          ph="main"
          uid="{43222D12-08C9-453B-AE96-D406EBB95126}" />
        <r
          ds=""
          id="{CE4ADCFB-7990-4980-83FB-A00C1E3673DB}"
          par=""
          ph="/main/centercolumn"
          uid="{CF044AD9-0332-407A-ABDE-587214A2C808}" />
        <r
          ds=""
          id="{493B3A83-0FA7-4484-8FC9-4680991CF743}"
          par=""
          ph="/main/centercolumn/content"
          uid="{B343725A-3A93-446E-A9C8-3A2CBD3DB489}" />
      </d>
      <d
        id="{46D2F427-4CE5-4E1F-BA10-EF3636F43534}"
        l="{14030E9F-CE92-49C6-AD87-7D49B50E42EA}">
        <r
          ds=""
          id="{493B3A83-0FA7-4484-8FC9-4680991CF743}"
          par=""
          ph="content"
          uid="{A08C9132-DBD1-474F-A2CA-6CA26A4AA650}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20061024T104300
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "6e071ebb-b706-4ca6-aba3-c87e9c1db5a9"
    - ID: "914aca44-8462-4816-99bf-adc35bf17dd0"
      Hint: PageTitle
      Value: $name
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\superuser
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210831T220806Z
