---
ID: "5912b0c5-0dde-4508-a307-3c13cef849cf"
Parent: "8218b4e3-0fbe-4f04-96e8-6c4f1a94d126"
Template: "e43e2773-7a50-4145-a266-312024f27382"
Path: "/sitecore/system/Modules/CMP/Config/Speaker Type/Content-Name"
BranchID: "875e0f89-f23b-476b-9bf9-e991a107f693"
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 50
- ID: "da990633-7884-44a2-8638-94389c5cbfec"
  Hint: CMP Field Name
  Value: TaxonomyName
- ID: "db99415a-fe86-4a2d-9583-db92894cb80a"
  Hint: Sitecore Field Name
  Value: "{B5E02AD9-D56F-4C41-A065-A133DB87BDEB}"
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{26849388-6BC3-43A2-8C40-8976C1705D45}"
Languages:
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: __Display name
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "73e4907c-eec8-41b1-b209-9ef2ff758991"
