---
ID: "016a0a40-4ccb-47a9-83b9-8dabb97ef2f2"
Parent: "8e7f4f7d-8ac7-435a-bb13-8212313c98d4"
Template: "8e7f4f7d-8ac7-435a-bb13-8212313c98d4"
Path: /sitecore/templates/Project/PLAY Summit/JSS Settings/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220511T191836Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\sitecoredemo@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\sitecoredemo@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "5ec79157-6097-45d5-87c7-ac0994d0750d"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\sitecoredemo@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220511T191836Z
