---
ID: "6c1b5e29-4ace-483a-8a84-333ae995b126"
Parent: "f8843bf7-a31a-4f71-8900-abd56b8fe34c"
Template: "e022206a-3482-46c2-8ddf-2f1c2c6c7b69"
Path: /sitecore/system/Modules/CMP/Config/Testimony
SharedFields:
- ID: "3f883dcb-c341-4929-9216-d07f4f1b00be"
  Hint: Bucket
  Value: "{70756637-66A4-49BB-9E8B-99BB99662E69}"
- ID: "9e009c2f-ad3c-4108-aa48-15689c1d4e1b"
  Hint: EntityTypeSchema
  Value: Demo.Testimony
- ID: "e82af1d8-7521-47e2-9e1b-898e5686d1c2"
  Hint: ItemNameProperty
  Value: Name
- ID: "e9c95e69-0d3d-4ae3-b893-d1ff4ba36b03"
  Hint: Template
  Value: "{905B44F3-DB0D-4050-A738-1ECE2EBB8509}"
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{74999BBB-92D6-4485-8168-3B32790768FC}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190614T173120Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\superuser
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\superuser
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1a10d370-f28e-4d43-bc4d-9efe970d78f3"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\superuser
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210730T220259Z
