---
ID: "4e9b9f13-7613-44c9-8402-2943fec94906"
Parent: "f8843bf7-a31a-4f71-8900-abd56b8fe34c"
Template: "e022206a-3482-46c2-8ddf-2f1c2c6c7b69"
Path: /sitecore/system/Modules/CMP/Config/Timeslot
SharedFields:
- ID: "3f883dcb-c341-4929-9216-d07f4f1b00be"
  Hint: Bucket
  Value: "{B541C1AE-68E3-484B-BC05-73B574497189}"
- ID: "9e009c2f-ad3c-4108-aa48-15689c1d4e1b"
  Hint: EntityTypeSchema
  Value: Demo.Timeslot
- ID: "e82af1d8-7521-47e2-9e1b-898e5686d1c2"
  Hint: ItemNameProperty
  Value: TaxonomyName
- ID: "e9c95e69-0d3d-4ae3-b893-d1ff4ba36b03"
  Hint: Template
  Value: "{0BC9237D-12EB-47A5-AFED-A65188324358}"
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{74999BBB-92D6-4485-8168-3B32790768FC}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "eb4f95af-f5af-4f20-81d0-b50ad4da665d"
