---
ID: "2de46343-6a33-58a9-8076-7b2ab5737737"
Parent: "6db09cef-64a8-52a3-a980-38408109c4d7"
Template: "6db09cef-64a8-52a3-a980-38408109c4d7"
Path: /sitecore/templates/Project/edgewebsite/Webpage/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{4AFA104F-090A-438E-AF07-8134D5D27DD9}"
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{8F0E1432-3729-462B-AD20-DAF067694BCB}"
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{B103F257-71EF-5392-B6CD-EC8062F68C1C}">
        <p
          uid="{163E0283-B986-57A3-BEB9-0FDA01E0FCD2}"
          key="jss-header-content"
          md="{B0B0F437-11AB-50B9-93D7-9D73EA3C3BD0}" />
        <p
          uid="{C679C0A2-921C-5D4C-B3CB-946E0484E6F9}"
          key="jss-section-content"
          md="{3ACD7D8D-E5D3-5AF6-BA34-BB869657E602}" />
        <p
          uid="{ED118F1D-A09D-4C65-9C17-C78B9AF7D3A1}"
          key="jss-summit-features-content"
          md="{C8C6EFD2-E574-4FD9-8833-4C5D6A23042F}" />
        <p
          uid="{A1C3B825-8C7A-5D67-85AF-D877DA0A1816}"
          key="jss-header"
          md="{2BDBF7A5-2830-586D-BADB-95A33FA429A3}" />
        <p
          uid="{4C73E177-7D69-56C2-86DA-2945966D7A9A}"
          key="jss-main"
          md="{83F8CCFF-EDAA-516B-BD68-71A16A354F42}" />
        <p
          uid="{8C6B98B5-1E4D-5868-9019-BF85141D3ABC}"
          key="jss-footer"
          md="{CC2CF2D1-033E-5D27-BA34-254D30F146CD}" />
        <r
          rname="Header"
          id="{0FC536D1-7D7C-579C-953B-454A308B4390}"
          par=""
          ph="/jss-header"
          uid="{1CB49545-D7F4-538D-9748-FAAD4753D3CB}" />
        <r
          rname="MainNavigation"
          id="{09516A66-F92F-5638-B073-8F9A79765778}"
          par=""
          ph="/jss-header/jss-header-content-{1CB49545-D7F4-538D-9748-FAAD4753D3CB}-0"
          uid="{7CDC810E-AE54-5B4B-BA7D-128CF6F96EDA}" />
        <r
          rname="Section"
          ds="{23C00813-F14B-5E8D-9102-EB409B5E1878}"
          id="{2F9D05FD-8E58-56CC-B586-41A3EC155CD7}"
          par=""
          ph="/jss-main"
          uid="{0761E527-92C1-596B-914B-DD9C282DA709}" />
        <r
          rname="NewsGrid"
          ds="{0E4A63DA-7496-557E-BF80-5BD52255E431}"
          id="{82A8BF89-B0DD-59EE-BC00-B1EF4525A6FD}"
          par=""
          ph="/jss-main/jss-section-content-{0761E527-92C1-596B-914B-DD9C282DA709}-0"
          uid="{DC2D2F9B-A6D1-5B5E-816E-4B402551810C}" />
        <r
          rname="Section"
          ds="{174A7AFC-D923-58F3-BEF8-AD8CAAD8C5B9}"
          id="{2F9D05FD-8E58-56CC-B586-41A3EC155CD7}"
          par=""
          ph="/jss-main"
          uid="{63AC6E75-5365-5E24-9E53-508B20613F45}" />
        <r
          rname="SelectedSponsorsGrid"
          ds="{F8952B14-1095-45FB-B7D9-6AE55AB2934D}"
          id="{4C6CFD83-311B-5EA6-8F55-AA03251D5232}"
          par=""
          ph="/jss-main/jss-section-content-{63AC6E75-5365-5E24-9E53-508B20613F45}-0"
          uid="{05991ACA-495A-5CED-B24C-2BC1F1D55D1A}" />
        <r
          rname="Footer"
          id="{ADBF0452-8883-5D03-877B-9F5C2E89725C}"
          par=""
          ph="/jss-footer"
          uid="{49649979-09D8-545A-AF70-2E50E065D19F}" />
      </d>
    </r>
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "78e8cf99-b9ab-4f68-80e7-b64a24ccc93f"
    - ID: "ed69eacf-5eb2-5050-9d5b-997812318dde"
      Hint: pageTitle
      Value: $name
