---
ID: "aa2c366a-742d-4496-b7de-3b465c7943f3"
Parent: "6b835483-0d83-4a75-a4f2-7743cd6d588e"
Template: "e43e2773-7a50-4145-a266-312024f27382"
Path: /sitecore/system/Modules/CMP/Config/Speaker/Page Title
BranchID: "70eb42ee-92b2-4246-bc65-aa920bb7f322"
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 0
- ID: "da990633-7884-44a2-8638-94389c5cbfec"
  Hint: CMP Field Name
  Value: Name
- ID: "db99415a-fe86-4a2d-9583-db92894cb80a"
  Hint: Sitecore Field Name
  Value: "{ED69EACF-5EB2-5050-9D5B-997812318DDE}"
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{4C94598B-EB37-400C-88C3-BEB971888C9A}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211005T121540Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\superuser
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\superuser
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1e2b6866-10c8-449d-80c4-85d16dc02d4a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\superuser
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20211005T121929Z
