---
ID: "8ff19c90-ed8e-4ec5-993c-545f6a1bdca4"
Parent: "7756380e-cb33-4213-b486-b73092696756"
Template: "7756380e-cb33-4213-b486-b73092696756"
Path: /sitecore/templates/Project/PLAY Summit/Page Designs/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {A58EF6DA-619E-4688-BB21-363038944569}
    {1105B8F8-1E00-426B-BF1F-C840742D827B}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220511T191835Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\sitecoredemo@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\sitecoredemo@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "23636c7b-e542-43c3-bd2f-3d0fe9c28fd0"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\sitecoredemo@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220511T191836Z
