---
ID: "dea04878-0854-46e8-a6ff-cdcdd960e3b9"
Parent: "26385370-1739-4f4f-84c0-cbd96e9514c0"
Template: "26385370-1739-4f4f-84c0-cbd96e9514c0"
Path: /sitecore/templates/Project/PLAY/App Route/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {26385370-1739-4F4F-84C0-CBD96E9514C0}
    {C14B6289-8AC2-439C-9E5B-40DE9F820C3F}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220511T191835Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\sitecoredemo@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\sitecoredemo@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "82fe4c72-c4a6-48c7-a8d5-83c719199b25"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\sitecoredemo@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220511T191837Z
    - ID: "e44ef569-9a34-4219-af40-3d0529984022"
      Hint: Title
      Value: $name
