---
ID: "9ed598e0-fe64-4a42-947b-df3ce6189ace"
Parent: "504cac9b-0e68-4bb2-93de-28590cb0dd8a"
Template: "8e7f4f7d-8ac7-435a-bb13-8212313c98d4"
Path: /sitecore/content/PLAY Summit/PLAY Website/Settings
BranchID: "45cf9f42-b3ac-4412-aab9-f8441c7e448e"
SharedFields:
- ID: "0129da3f-8c86-4591-ae32-6ec923413923"
  Hint: DictionaryDomain
  Value: "{9127A604-9F3E-4CFF-A6C5-E04C5FA8BD76}"
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{C2DC4690-AF44-48C7-BB21-90D1AD246732}"
- ID: "1864e99d-c29a-40bf-96e0-b3e7896a013b"
  Hint: UseLanguageSpecificLayout
  Value: 1
- ID: "300fb7a0-b27f-44dd-9af0-b37a19723e0e"
  Hint: RouteTemplateName
  Value: Settings Route
- ID: "30e0a829-637e-478c-a136-66adb568398d"
  Hint: GraphQLEndpoint
  Value: /sitecore/api/graph/edge
- ID: "32ce6bbe-4217-46e5-9335-42793884cbe3"
  Hint: AppTemplate
  Value: "{507B2363-3200-4CEA-B238-3045731BA6A5}"
- ID: "3af0e329-6d5e-4d8f-9f82-f48265658a3e"
  Hint: DefaultWorkflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
- ID: "3e4f559f-8e59-4405-b50d-619811371f6c"
  Hint: Name
  Value: edgewebsite
- ID: "5764d2d4-724d-4313-a81b-9246c911faff"
  Hint: AppDatasourcesPath
  Value: "{44864379-85FA-46DF-A102-35A8BC2391B5}"
- ID: "5ca117eb-8782-4a4f-9f2f-30de31fc2e34"
  Hint: PlaceholdersPath
  Value: "{B63FE2F1-B5CA-481F-8D7C-CC11BF1DABF8}"
- ID: "5e8ed724-126a-4bb7-8106-85c2d1042c9e"
  Hint: ServerSideRenderingEngineApplicationUrl
  Value: 
- ID: "72e83c8d-3578-4e50-b4c0-93a78a1729f2"
  Hint: FilesystemPath
  Value: /dist/edgewebsite
- ID: "797d2f63-d5c4-4c4c-b21f-d3e250e2ab12"
  Hint: DeploymentSecret
  Value: 
- ID: "89849738-34ee-46bc-b525-825f1153189e"
  Hint: ServerSideRenderingEngineEndpointUrl
  Value: 
- ID: "9016141c-ff51-40f2-9135-40f5161b9784"
  Hint: ServerSideRenderingEngine
  Value: http
- ID: "a7bbad73-b933-49ff-95c8-1c269cb35e7c"
  Hint: DictionaryPath
  Value: "{9127A604-9F3E-4CFF-A6C5-E04C5FA8BD76}"
- ID: "b0711df7-724a-4c6c-8d4d-be846de6124c"
  Hint: ProtectDeveloperItems
  Value: 
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 2000
- ID: "c8d002f9-9518-4c5e-9baa-6617e13f0797"
  Hint: LayoutPath
  Value: "{96E5F4BA-A2CF-4A4C-A4E7-64DA88226362}"
- ID: "e3259313-387a-41f0-b113-962f14b1aa2b"
  Hint: LayoutServiceConfiguration
  Value: "sxa-jss"
- ID: "e8881464-38af-4655-be4a-ee10586578a2"
  Hint: Templates
  Value: "{348162CF-D211-43B5-A745-DC5C8F62D677}"
- ID: "f29428d5-1285-48b8-a884-44057965829a"
  Hint: RenderingsPath
  Value: "{D876FFEC-E6EE-479C-9F3A-A75A67FC4471}"
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{0FEEB907-58F0-44DE-B08C-2F43C063D0A5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220511T192047Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\sitecoredemo@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\sitecoredemo@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e1299e36-8d86-44fe-b4d4-c0581f24f084"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\sitecoredemo@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220513T212827Z
