---
ID: "45f73ae9-dc5c-462e-a4d6-3b847828a754"
Parent: "077d35d0-1c1e-44f6-9cef-4a1738e27cb4"
Template: "077d35d0-1c1e-44f6-9cef-4a1738e27cb4"
Path: /sitecore/templates/Project/edgewebsite/Landing Page/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {4AFA104F-090A-438E-AF07-8134D5D27DD9}
    {6DB09CEF-64A8-52A3-A980-38408109C4D7}
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{8F0E1432-3729-462B-AD20-DAF067694BCB}"
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{B103F257-71EF-5392-B6CD-EC8062F68C1C}">
        <p
          uid="{163E0283-B986-57A3-BEB9-0FDA01E0FCD2}"
          key="jss-header-content"
          md="{B0B0F437-11AB-50B9-93D7-9D73EA3C3BD0}" />
        <p
          uid="{A1C3B825-8C7A-5D67-85AF-D877DA0A1816}"
          key="jss-header"
          md="{2BDBF7A5-2830-586D-BADB-95A33FA429A3}" />
        <p
          uid="{4C73E177-7D69-56C2-86DA-2945966D7A9A}"
          key="jss-main"
          md="{83F8CCFF-EDAA-516B-BD68-71A16A354F42}" />
        <p
          uid="{8C6B98B5-1E4D-5868-9019-BF85141D3ABC}"
          key="jss-footer"
          md="{CC2CF2D1-033E-5D27-BA34-254D30F146CD}" />
        <r
          rname="Header"
          id="{0FC536D1-7D7C-579C-953B-454A308B4390}"
          par=""
          ph="/jss-header"
          uid="{1CB49545-D7F4-538D-9748-FAAD4753D3CB}" />
        <r
          rname="MainNavigation"
          id="{09516A66-F92F-5638-B073-8F9A79765778}"
          par=""
          ph="/jss-header/jss-header-content-{1CB49545-D7F4-538D-9748-FAAD4753D3CB}-0"
          uid="{7CDC810E-AE54-5B4B-BA7D-128CF6F96EDA}" />
        <r
          rname="Footer"
          id="{ADBF0452-8883-5D03-877B-9F5C2E89725C}"
          par=""
          ph="/jss-footer"
          uid="{49649979-09D8-545A-AF70-2E50E065D19F}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210615T142040Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "569d9c31-59c8-457c-a78c-d51e52a17122"
      Hint: pageTitle
      Value: $name
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "58a47004-f216-426d-8e2e-10253911c7d4"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\superuser
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220613T153236Z
- Language: "fr-CA"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220406T211750Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "413d726b-40b1-4826-872b-4ebf6c8d6421"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220406T211750Z
