---
ID: "042538b9-4057-47c6-a094-1df752dc0d5f"
Parent: "6b835483-0d83-4a75-a4f2-7743cd6d588e"
Template: "e43e2773-7a50-4145-a266-312024f27382"
Path: /sitecore/system/Modules/CMP/Config/Edge Speaker/Instagram Profile Link
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 200
- ID: "da990633-7884-44a2-8638-94389c5cbfec"
  Hint: CMP Field Name
  Value: e31bd_InstagramProfileLink
- ID: "db99415a-fe86-4a2d-9583-db92894cb80a"
  Hint: Sitecore Field Name
  Value: "{CBA0963A-F0DA-4AB1-A996-5BC727C9D9F1}"
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: 
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190614T174224Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "8e488e01-9476-4629-bed8-6007bda75b40"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\superuser
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210725T112147Z
