---
ID: "599bd7d0-077f-48c8-ace7-e18d3ea41063"
Parent: "6aa1ece5-d4a4-4458-a534-e6543863e341"
Template: "6aa1ece5-d4a4-4458-a534-e6543863e341"
Path: /sitecore/templates/Project/PLAY Summit/Partial Design Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {6AA1ECE5-D4A4-4458-A534-E6543863E341}
    {FD2059FD-6043-4DFE-8C04-E2437CE87634}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220511T191835Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\sitecoredemo@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\sitecoredemo@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c2af7802-2478-4f96-9d5d-f6cf5407fcba"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\sitecoredemo@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220511T191836Z
