---
ID: "7681796b-a800-4fc1-b0b4-065f8baeabf9"
Parent: "a06b2851-c98a-4622-8773-98736daadb13"
Template: "a06b2851-c98a-4622-8773-98736daadb13"
Path: /sitecore/templates/Project/edgewebsite/CMP Entities/Venue/__Standard Values
SharedFields:
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: 
- ID: "c9283d9e-7c29-4419-9c28-5a5c8ff53e84"
  Hint: __Bucketable
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190614T161122Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{C55B483C-EA7F-4E76-A066-985F7D9396CA}"
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "fa655cad-df05-4cbc-844d-f88a26222fc1"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\superuser
    - ID: "c61b8113-e6e4-4d25-a768-85febbe750da"
      Hint: ImageTransformation
      Value: web
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20211116T174750Z
    - ID: "fc3b2a6c-042b-421c-9c3d-88c83186ceb9"
      Hint: Name
      Value: $name
